export const COMPLETION_BEEP_FREQUENCY = 880;
export const COMPLETION_BEEP_DURATION_MS = 200;

export const WARNING_BEEP_FREQUENCY = 1320;
export const WARNING_BEEP_DURATION_MS = 200;
export const WARNING_THRESHOLD_MS = 10_000;

export const SIDE_SWITCH_BEEP_FREQUENCY = 1040;
export const SIDE_SWITCH_BEEP_DURATION_MS = 450;
export const SIDE_SWITCH_DOUBLE_BEEP_DELAY_MS = 200;
export const MIN_WARNING_GAP_AFTER_SWITCH_MS = 8_000;
export const SIDE_SWITCH_CUE_DELAY_MS = 300;
export const SIDE_SWITCH_VISUAL_DURATION_MS = 4_000;
